[build]
command = "npm run build && cp -r client/public/* dist/ && mkdir -p functions-build && esbuild functions/server.js --platform=node --packages=external --bundle --outfile=functions/server.js"
publish = "dist"
node_bundler = "esbuild"

[build.environment]
NODE_VERSION = "20"

[functions]
directory = "functions"

[routes]
pattern = "/api/*"
function = "server"

[site]
bucket = "./dist"