name = "porto-feb-api"
compatibility_date = "2023-12-01"
compatibility_flags = ["nodejs_compat"]
workers_dev = true
main = "./functions/server.js"

[build]
command = "npm run build && cp -r client/public/* dist/ && mkdir -p functions-build && esbuild functions/server.js --platform=node --packages=external --bundle --outfile=functions/server.js"

[site]
bucket = "./dist"

[vars]
NODE_ENV = "production"